!!! ajax now working
zealot9000/stackoverflow-clone pull request #4
Opened 2017-06-17 12:31 UTC by zealot9000

2017-06-17 15:32 UTC, vkurennov requested changes

2017-06-17 15:32 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    redirect_to @question, notice: 'Your answer successfully created.'
В ajax нет смысла делать редирект, потому что он в фоне выполняется и браузер ничего не делает. Тут надо возвращать js-ответ (create.js.erb), и в нем добавлять созданный ответ на страницу

2017-06-17 15:32 UTC, vkurennov commented on app/views/answers/create.js.erb
> +$('.answers').html('<%= j render 'questions/answers' %>');
Вспомни про анонимные паршалы: сделай паршл для одного ответа и добавляй только его к списку, а не рендери весь список повторно

2017-06-17 15:32 UTC, vkurennov commented on spec/features/create_answer_spec.rb
> +  scenario 'Authenticated user create answer', js: true do
А тесты контроллера? Там тоже надо  js-запросы делать

2017-06-22 09:37 UTC, vkurennov requested changes

2017-06-22 09:37 UTC, vkurennov commented on app/controllers/users/confirmations_controller.rb
> +class Users::ConfirmationsController < Devise::ConfirmationsController
Удали неиспользуемые контроллеры devise

2017-06-22 09:37 UTC, vkurennov commented on app/views/answers/create.js.erb
> +$('.answers').html('<%= j render 'questions/answers' %>');
Не исправлено

2017-06-22 09:37 UTC, vkurennov commented on app/views/questions/_answers.html.slim
> +  - if answer.persisted?
Сделай паршл для одного ответа, перенеси его в answers/_answer, это и будет анонимный паршл, тогда один ответ можно будет ренедрить так: 

`render @answer`

а список так: `render @question.answers`

2017-06-23 06:56 UTC, vkurennov requested changes

2017-06-23 06:56 UTC, vkurennov commented on app/views/answers/create.js.erb
> +$('.answers').html('<%= j render @answer %>');
Так ты весь список заменишь одним ответом, а надо его добавлять к существующему списку (функция  append)

2017-06-23 09:10 UTC, zealot9000 commented on app/views/answers/create.js.erb
> +$('.answers').html('<%= j render @answer %>');
а я рендерю список ответов до нового ответа: 

```
= render @question.answers

 .answers
```

2017-06-26 18:30 UTC, merged